name: upload-to-azure-storage-account

permissions:
  contents: read
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  account_key:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - run: |
          touch file1.txt
          touch file2.txt
          touch file1.py
          touch file2.py

      - name: upload with account key
        run: |
          az storage blob upload-batch \
            -d upload-actions \
            --account-name geijosh \
            --account-key ${{ secrets.ACCOUNT_KEY }} \
            -s . \
            --pattern "*.txt"

  oidc:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}
          
      - name: upload with odic
        run: |
          az storage blob upload-batch \
            -d upload-actions-oidc \
            --account-name geijosh \
            -s . \
            --pattern "*.py"
